### ISSUE TITLE
Dependency on plenary not specified.

### ISSUE THREAD

**Issue by sultanahamer** [nagy135/typebreak.nvim#1]
Could you please specify that this plugin requries plenary in installation. Ofcourse many of the neovimmers would have plenary already added to their config.

Today I was trying out neovide on a different computer and saw your post on reddit. Tried this on empty config and it failed.

Also this is a windows computer and not sure if plenary's curl will require a windows curl library or a luarocks thing,

Also, I thought words are generated on local system. :)

**Comment by nagy135** [comment]
Totally! Tbh just yesterday I switched to Packer and still trying to figure out what depends on what.
The idea for this plugin was because I just found out about that api and heard abour new neovim api to create windows like this.
