### ISSUE TITLE
Dictionary selection

### ISSUE THREAD

**Issue by aslak01** [nagy135/typebreak.nvim#2]
I like the plugin a lot, but I find the word list is rather esoteric. It can sometimes be as much of a challenge for me to read and understand the words as getting these old, stiff fingers to reach their weird keyboard positions. And I enjoy the challenge in that, but I'd also like to use the plugin as a kinda finger warmup tool with a bit of a lower cognitive load. That's why I think it'd be a neat feature to be able to select a dictionary it choses from, with perhaps more programming adjacent words for that kind of situation. Later in the day when my head is a bit more in the game and I want a break from those kinds of words, the current list is perfect, but for sleepy mornings… maybe it's just me idk.

**Comment by nagy135** [comment]
I feel ya, the reason why words are as they are is that the whole reason I made this plugin is that i found this api [https://random-word-api.herokuapp.com/word?number=10](https://github.com/nagy135/typebreak.nvim/blob/master/lua/typebreak/init.lua#L65)

I dislike idea where I would ship entire dictionary as a part of the plugin. It might have some advantages (like not needing internet connection).

I think the middleground I could easily add is option to pass your own dictionary from `setup()` that would override heroku api calls with simple random pick from your dictionary.

Does that sound like a good idea to you?

**Comment by nagy135** [comment]
I would also add that i kinda grew to like those words ...it makes it little bit of a challenge and I learned o lot of new words using this for months. So this might at most be "opt out" change

**Comment by aslak01** [comment]
What I was imagining was a way to chose the dictionary from within the type break window, not having to go into settings.

Also thinking about the api thing, I think a nice middle ground would be to ship a small word list with the plugin, and have the other selectable sources be apis. I did a small search on GitHub and found a Chinese typing game word list with full translations and explanations of several thousand words in json was not prohibitively big, like 200kb. So a less extensive list without additional info shouldn't really be a problem to ship imo. 

Edit: also don't feel like you need to implement this fast or at all, I just wanted to suggest something I thought would be an improvement.

**Comment by nagy135** [comment]
i get your point, will try to come up with something in day or two :) but as i said, opt out ... i ll probably add one flag "dont_use_dictionary_api" that will use lets say 100 words ...with additional field to supply your dictionary.

I m not gonna do any UI for this i dont see reason to complicate things.
If you wanna contribute, give me those 100 words or even create PR :)

**Comment by aslak01** [comment]
> I would also add that i kinda grew to like those words ...it makes it little bit of a challenge and I learned o lot of new words using this for months. So this might at most be "opt out" change

Yeah I like the words too, and I was imagining the ux of another dictionary as: It boots with the complex words, but if you're feeling a bit tired in the brain you have the ability to summon a menu and get words that are less intensive on the linguistic cortex.

**Comment by nagy135** [comment]
that sounds like a good point but i like how it instantly starts ...we could add argument to start function so you could have separate bind. I use [key-menu](https://github.com/linty-org/key-menu.nvim) that gives me something like UI when binds have same prefix, you could use it too

**Comment by aslak01** [comment]
I mean, doesn't need to be a ui menu, some bindable function or something would be fine. Key menu looks neat but maybe kinda obscure as a dependency?

**Comment by nagy135** [comment]
nono, key-menu is not dependency, it btw automatically fetches all your binds, that would piss off everyone xD that was just suggestion for you

https://github.com/nagy135/typebreak.nvim#custom-dictionary
give it a shot

**Comment by nagy135** [comment]
i like how much faster it is without api calls, but its too easy :( i used this to get words
https://randomwordgenerator.com/

**Comment by aslak01** [comment]
How about this list maybe? https://github.com/gokhanyavas/Oxford-3000-Word-List/blob/master/Oxford%203000%20Word%20List%20No%20Spaces.txt

**Comment by nagy135** [comment]
looks good, i m just very new to lua i have no idea if table with 30KB size wouldnt cause some issues, and my time is kinda limited now. I will close this for now and will replace it in few days if it doesnt cause any issues :) for now you can do it yourself in your config

**Comment by aslak01** [comment]
have a look at this: `/usr/share/dict/words`
