### ISSUE TITLE
The `<Leader>tb` doesn't seem to start the game

### ISSUE THREAD

**Issue by nyngwang** [nagy135/typebreak.nvim#3]
As title. It shows this:

<img src="https://user-images.githubusercontent.com/24765272/204817845-46c0636a-2dde-4c30-83b9-5fa0f8c0f954.png" width="500">

**Comment by nagy135** [comment]
Thanks for report ...its just api for fetching those words changed for some reason. Fixed.
I didnt notice, i use [custom dictionary instead](https://github.com/nagy135/typebreak.nvim#custom-dictionary)

**Comment by nyngwang** [comment]
@nagy135 Thanks for maintaining this game!
